embed = struct( 'X', rand(10,1), ...
        'Y', rand(10,1), ...
        'src', { arrayfun( ...
                @(x)fullfile( '.',  ...
                'assets',  ...
                sprintf( 'img-%2i.jpg', x ) ), ...
                1: 10, ...
                'UniformOutput', false ) } );
            
s = savejson( embed );

fo = fopen( 'img.json', 'w'); fwrite( fo, s ); fclose( fo );
%% Test images 

mkdir( './assets');

for ii = 1 : 10 
    fn = fullfile( '.',  ...
                'assets',  ...
                sprintf( 'img-%2i.jpg', ii ) )
    
    % Write random images
    urlwrite('http://lorempixel.com/200/200/',fn)
end